/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author 222397
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    Float valor1, valor2;
    String operacao;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bot_igual = new javax.swing.JButton();
        bot_zero = new javax.swing.JButton();
        bot_ce = new javax.swing.JButton();
        bot_div = new javax.swing.JButton();
        bot_mais = new javax.swing.JButton();
        bot_menos = new javax.swing.JButton();
        bot_mult = new javax.swing.JButton();
        bot_nove = new javax.swing.JButton();
        bot_seis = new javax.swing.JButton();
        bot_tres = new javax.swing.JButton();
        bot_dois = new javax.swing.JButton();
        bot_cinco = new javax.swing.JButton();
        bot_oito = new javax.swing.JButton();
        bot_sete = new javax.swing.JButton();
        bot_quatro = new javax.swing.JButton();
        bot_um = new javax.swing.JButton();
        tela = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bot_igual.setText("=");
        bot_igual.setAlignmentX(0.5F);
        bot_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_igualActionPerformed(evt);
            }
        });

        bot_zero.setText("0");
        bot_zero.setAlignmentX(0.5F);
        bot_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_zeroActionPerformed(evt);
            }
        });

        bot_ce.setText("CE");
        bot_ce.setAlignmentX(0.5F);
        bot_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_ceActionPerformed(evt);
            }
        });

        bot_div.setText("/");
        bot_div.setAlignmentX(0.5F);
        bot_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_divActionPerformed(evt);
            }
        });

        bot_mais.setText("+");
        bot_mais.setAlignmentX(0.5F);
        bot_mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_maisActionPerformed(evt);
            }
        });

        bot_menos.setText("-");
        bot_menos.setAlignmentX(0.5F);
        bot_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_menosActionPerformed(evt);
            }
        });

        bot_mult.setText("x");
        bot_mult.setAlignmentX(0.5F);
        bot_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_multActionPerformed(evt);
            }
        });

        bot_nove.setText("9");
        bot_nove.setAlignmentX(0.5F);
        bot_nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_noveActionPerformed(evt);
            }
        });

        bot_seis.setText("6");
        bot_seis.setAlignmentX(0.5F);
        bot_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_seisActionPerformed(evt);
            }
        });

        bot_tres.setText("3");
        bot_tres.setAlignmentX(0.5F);
        bot_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_tresActionPerformed(evt);
            }
        });

        bot_dois.setText("2");
        bot_dois.setAlignmentX(0.5F);
        bot_dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_doisActionPerformed(evt);
            }
        });

        bot_cinco.setText("5");
        bot_cinco.setAlignmentX(0.5F);
        bot_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cincoActionPerformed(evt);
            }
        });

        bot_oito.setText("8");
        bot_oito.setAlignmentX(0.5F);
        bot_oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_oitoActionPerformed(evt);
            }
        });

        bot_sete.setText("7");
        bot_sete.setAlignmentX(0.5F);
        bot_sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_seteActionPerformed(evt);
            }
        });

        bot_quatro.setText("4");
        bot_quatro.setAlignmentX(0.5F);
        bot_quatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_quatroActionPerformed(evt);
            }
        });

        bot_um.setText("1");
        bot_um.setAlignmentX(0.5F);
        bot_um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_umActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tela, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bot_sete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bot_oito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bot_nove, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bot_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bot_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bot_quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(bot_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bot_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bot_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(bot_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bot_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bot_div, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(bot_um, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bot_dois, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bot_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bot_mais, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bot_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_nove, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_oito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_sete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bot_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bot_mais, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_dois, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_um, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bot_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_div, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_igualActionPerformed
        valor2= Float.parseFloat(tela.getText());
        
        if(operacao == "Soma"){
            tela.setText(String.valueOf(valor1 + valor2));
        }else if(operacao == "Subtração"){
            tela.setText(String.valueOf(valor1 - valor2));
        }else if(operacao == "Multiplicação"){
            tela.setText(String.valueOf(valor1 * valor2));            
        }else if(operacao == "Divisão")
                tela.setText(String.valueOf(valor1 / valor2));
    }//GEN-LAST:event_bot_igualActionPerformed

    private void bot_zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_zeroActionPerformed
        // TODO add your handling code here:
        tela.setText(tela.getText() + "0" );
    }//GEN-LAST:event_bot_zeroActionPerformed

    private void bot_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_ceActionPerformed
        tela.setText(" ");
    }//GEN-LAST:event_bot_ceActionPerformed

    private void bot_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_divActionPerformed
        valor1 = Float.parseFloat(tela.getText());
        tela.setText(" ");
        operacao = "Divisão";
    }//GEN-LAST:event_bot_divActionPerformed

    private void bot_maisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_maisActionPerformed
        valor1 = Float.parseFloat(tela.getText());
        tela.setText(" ");
        operacao = "Soma";
    }//GEN-LAST:event_bot_maisActionPerformed

    private void bot_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_menosActionPerformed
        valor1 = Float.parseFloat(tela.getText());
        tela.setText(" ");
        operacao = "Subtração";
    }//GEN-LAST:event_bot_menosActionPerformed

    private void bot_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_multActionPerformed
        valor1 = Float.parseFloat(tela.getText());
        tela.setText(" ");
        operacao = "Multiplicação";
    }//GEN-LAST:event_bot_multActionPerformed

    private void bot_noveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_noveActionPerformed
       tela.setText(tela.getText() + "9" );
    }//GEN-LAST:event_bot_noveActionPerformed

    private void bot_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_seisActionPerformed
        tela.setText(tela.getText() + "6" );
    }//GEN-LAST:event_bot_seisActionPerformed

    private void bot_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_tresActionPerformed
        tela.setText(tela.getText() + "3" );
    }//GEN-LAST:event_bot_tresActionPerformed

    private void bot_doisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_doisActionPerformed
        tela.setText(tela.getText() + "2" );
    }//GEN-LAST:event_bot_doisActionPerformed

    private void bot_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cincoActionPerformed
       tela.setText(tela.getText() + "5" );
    }//GEN-LAST:event_bot_cincoActionPerformed

    private void bot_oitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_oitoActionPerformed
        tela.setText(tela.getText() + "8" );
    }//GEN-LAST:event_bot_oitoActionPerformed

    private void bot_seteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_seteActionPerformed
        tela.setText(tela.getText() + "7" );
    }//GEN-LAST:event_bot_seteActionPerformed

    private void bot_quatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_quatroActionPerformed
        tela.setText(tela.getText() + "4" );
    }//GEN-LAST:event_bot_quatroActionPerformed

    private void bot_umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_umActionPerformed
       tela.setText(tela.getText() + "1" );
    }//GEN-LAST:event_bot_umActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_ce;
    private javax.swing.JButton bot_cinco;
    private javax.swing.JButton bot_div;
    private javax.swing.JButton bot_dois;
    private javax.swing.JButton bot_igual;
    private javax.swing.JButton bot_mais;
    private javax.swing.JButton bot_menos;
    private javax.swing.JButton bot_mult;
    private javax.swing.JButton bot_nove;
    private javax.swing.JButton bot_oito;
    private javax.swing.JButton bot_quatro;
    private javax.swing.JButton bot_seis;
    private javax.swing.JButton bot_sete;
    private javax.swing.JButton bot_tres;
    private javax.swing.JButton bot_um;
    private javax.swing.JButton bot_zero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tela;
    // End of variables declaration//GEN-END:variables
}
